version: 2
updates:
  - package-ecosystem: "npm" # for JavaScript dependencies
    directory: "/" # location of package.json
    schedule:
      interval: "weekly" # how often to check for updates
    commit-message:
      prefix: "fix" # prefix for commit messages
    ignore:
      - dependency-name: "tauri" # specify the dependency to ignore, if any
        versions: ["<1.0.0"] # specify the versions to ignore
  - package-ecosystem: "cargo" # for Rust dependencies
    directory: "./src-tauri" # Updated to the correct location of Cargo.toml
    schedule:
      interval: "weekly" # how often to check for updates
    commit-message:
      prefix: "fix" # prefix for commit messages
